name: Compile Typst Documents
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Compile Typst Files
      uses: ammar-ahmed22/compile-typst-action@v1
      with:
        source_paths: 'src/al2/chuletario.typ src/tim/chuletario.typ'
        output_paths: './al2.pdf ./tim.pdf'
        # fonts_path: 'path/to/fonts'
